### ISSUE TITLE
FFmpeg's readvitc is not detecting VITCs for all frames output from Unai.VITC

### ISSUE THREAD

**Issue by bbgdzxng1** [unai-d/Unai.VITC#2]
Firstly, love the concept of the Unai.VITC tool.  Thank-you for putting this utility together.

I have successfully compiled the tool for macOS x86 using dotnet & .NET3.x using...
`$ dotnet publish -r osx-x64 -p:PublishSingleFile=true --self-contained true`

However, I am struggling to use the example commands on the README.md to create a result that produce a result that FFmpeg readvitc will recognize from the first frame.  Would you be kind enough to share the commands that you used to create the APNG examples?

Here is the command I ran (based on the example in README.md).  I have tried various framerates, padded inputs, overlays, unscaled, various scale-factors etc.  I have also tried using an intermediary file, rather than a pipe.

```
# Long command is broken up into separate lines with \ for readability on Github...
#
$ ./Unai.VITC -fps 25 -t "00:01:00:00" -tc "00:00:00:00" \
  | ffmpeg -hide_banner -report \
  -f "rawvideo" -video_size "90x1" -pixel_format "gray" -framerate 25 -i - \
  -filter:v "scale=width=360:height=4:flags=neighbor,readvitc=scan_max=-1,metadata=print:file=readvitc.txt" \
  -t "00:01:00.000" -f "null" - -y
$ cat readvitc.txt
```
[readvitc.txt - unexpected result](https://github.com/unai-d/Unai.VITC/files/7358599/readvitc.txt) is the output of readvitc filter showing that no VITC is identified until 4 seconds/100 frames into the file.  It then stops detecting at 5 seconds, then starts working at 10 seconds.
```
lavfi.readvitc.found=0
frame:99   pts:99      pts_time:3.96
lavfi.readvitc.found=0
frame:100  pts:100     pts_time:4
lavfi.readvitc.found=1
lavfi.readvitc.tc_str=00:00:04:00
frame:101  pts:101     pts_time:4.04
lavfi.readvitc.found=1
lavfi.readvitc.tc_str=00:00:04:01
frame:102  pts:102     pts_time:4.08
```
However, if I run FFmpeg against your animated PNG hosted samples on github, the VITC is detected and decoded from the first frame, as expected.  Here is the [working.txt](https://github.com/unai-d/Unai.VITC/files/7358598/working.txt) result.

```
$ ffmpeg -hide_banner -report \
-i "https://raw.githubusercontent.com/unai-d/Unai.VITC/main/img/readvitc-pal.png" \
-filter:v "readvitc=scan_max=-1,metadata=print:file=working.txt" \
-f "null" - -y
$ cat working.txt

frame:0    pts:0       pts_time:0
lavfi.readvitc.found=1
lavfi.readvitc.tc_str=00:00:00:00
frame:1    pts:4000    pts_time:0.04
lavfi.readvitc.found=1
lavfi.readvitc.tc_str=00:00:00:01
frame:2    pts:8000    pts_time:0.08
lavfi.readvitc.found=1
lavfi.readvitc.tc_str=00:00:00:02
frame:3    pts:12000   pts_time:0.12
```

I can imagine how you have used FFmpeg's readvitc, metadata, drawtext filters to create your animated PNGs.  I'm familiar with using metadata and drawtext filters.

Would you be kind enough to share your full command for generating the APNG's and try my command on your build, in case it is specific to my build.  I'm running a recent version of FFmpeg.

```
$ ffmpeg -version
ffmpeg version 4.4 Copyright (c) 2000-2021 the FFmpeg developers
built with Apple clang version 12.0.0 (clang-1200.0.32.29)
```

Thanks for the tool.  I've been looking for a tool to generate VITC and embed 608 captions as Line 21 for a few years.  Your project is the first open-source vitsee rendering tool.  Appreciated.

**Comment by bbgdzxng1** [comment]
That is great and I confirm it has solved the problem I was facing.  Thanks so much for sharing your command.  Awesome utility.

Hopefully, I'll find an equivalent line 21 608 encoder as excellent as this VITC encoder.

**Comment by SimeJah** [comment]
Hello you amazing people.. 
My programming skills are a bit too limited to get this working on my own..
Can someone please guide me through the proces on how I can generate a VITC video? I would be forever grateful! :)
