### ISSUE TITLE
could it be possible to add hacktv pipe support?

### ISSUE THREAD

**Issue by 03stevensmi** [unai-d/Unai.VITC#5]
would this project be able to generate the tbc from ether video or hacktv output and pipe it to the hacktv as input 
for use with analouge transmition?
https://github.com/fsphil/hacktv

could this be possible?

thank you.

Sincerly,
Michael

**Comment by unai-d** [comment]
With the latest commit (`6e0deca`) I was able to do it. Here's the command:

```
ffmpeg -re -f lavfi -i pal100bars=s=720x576 -f rawvideo -pix_fmt rgb24 - | \
Unai.VITC -s 720x576 -f R8G8B8 -I -i - | \
ffmpeg -f rawvideo -pixel_format rgb24 -video_size 720x576 -i - -f matroska -c:v mjpeg - | \
hacktv - -f 854e6 -g 24 -m b
```

- The first FFmpeg instance converts the input video to a format that `Unai.VITC` can understand (raw 24-bit RGB).
- Then, `Unai.VITC` embeds the VITC signal to the video (resolution is unchanged) and outputs the result in the same format.
- After that, the second FFmpeg instance converts the resulting video stream to a format that HackTV can understand (it uses FFmpeg for decoding anyway, so I guess you could change the parameters if you want).
- And finally, HackTV takes that stream and sends it to the HackRF.

Also, HackTV recently added support for VITC. Although it is not as customisable as this program, it's definitely closer to what an actual VITC signal looks like.

**Comment by 03stevensmi** [comment]
> 

thank you so much!
This is actully very helpful to know...
but i was refering to a generated and/or simulated tbc (Time Base Correction) for hacktv's basband composite output.

https://www.digitalfaq.com/forum/video-restore/2251-tbc-time-base.html#:~:text=A%20%27timebase%20corrector%27%20or%20%27time%20base%20corrector%27%20--,then%20it%20is%20corrected%20before%20being%20output%20again.

Would be interesting to see if this is accually possible with hacktv and Unai-VITC!

;)

**Comment by unai-d** [comment]
Oops... I didn't read the TBC part. But I still don't understand what does "generating the TBC" mean.

If you want to insert VITC signals into the baseband output of HackTV (something that looks like this)…:

![baseband-pal100bars](https://user-images.githubusercontent.com/70072019/215347990-afba052c-4ea5-45f1-a18a-3e5fb3151e5f.jpg)

…I can easily implement that in a future commit.

Now, video signal correction would require a totally different program, since this one only takes care of generating a VITC signal and optionally insert it into a video stream.

**Comment by harrypm** [comment]
@03stevensmi We have had fully software-defined TBC for composite signals for 3 years now and is widely in use via [vhs-decode](https://github.com/oyvindln/vhs-decode/) / [ld-decode](https://github.com/happycube/ld-decode/) & lastly Composite or [cvbs-decode](https://github.com/oyvindln/vhs-decode/wiki/CVBS-Composite-Decode) it has replaced using hardware TBCs for a while but LS doesn't really like that so digital FAQ is kinda in this post software era keeping outdated info alive lol.

We have the TBC format in 16-bit unsigned values `GREY16` you can use with SDR hardware, and you can make standard video into TBC files via the `ld-chroma-encoder` (there is also a windows release of the ld-tools suite btw) 

Example of the signal in CVBS

![frame_pal_source_1_CVBS-Level-2-CX-Card-Test tbc](https://user-images.githubusercontent.com/56382624/215357243-40105166-2bd3-47c4-89fa-88fb8ccb4fe6.png)

![frame_pal_chroma_1_CVBS-Level-2-CX-Card-Test tbc](https://user-images.githubusercontent.com/56382624/215357244-1ece6f39-d79d-4807-b3c7-34b71399745b.png)

VITC on SVHS

![frame_pal_source_1_Ebay-NV-S7-VHS-SP tbc](https://user-images.githubusercontent.com/56382624/215357453-f9d5b0a7-b58b-4be4-9781-2cb09304c565.png)

**Comment by 03stevensmi** [comment]
> @03stevensmi We have had fully software-defined TBC for composite signals for 3 years now and is widely in use via [vhs-decode](https://github.com/oyvindln/vhs-decode/) / [ld-decode](https://github.com/happycube/ld-decode/) & lastly Composite or [cvbs-decode](https://github.com/oyvindln/vhs-decode/wiki/CVBS-Composite-Decode) it has replaced using hardware TBCs for a while but LS doesn't really like that so digital FAQ is kinda in this post software era keeping outdated info alive lol.
> 
> We have the TBC format in 16-bit unsigned values `GREY16` you can use with SDR hardware, and you can make standard video into TBC files via the `ld-chroma-encoder` (there is also a windows release of the ld-tools suite btw)
> 
> Example of the signal in CVBS
> 
> ![frame_pal_source_1_CVBS-Level-2-CX-Card-Test tbc](https://user-images.githubusercontent.com/56382624/215357243-40105166-2bd3-47c4-89fa-88fb8ccb4fe6.png)
> 
> ![frame_pal_chroma_1_CVBS-Level-2-CX-Card-Test tbc](https://user-images.githubusercontent.com/56382624/215357244-1ece6f39-d79d-4807-b3c7-34b71399745b.png)
> 
> VITC on SVHS
> 
> ![frame_pal_source_1_Ebay-NV-S7-VHS-SP tbc](https://user-images.githubusercontent.com/56382624/215357453-f9d5b0a7-b58b-4be4-9781-2cb09304c565.png)

@harrypm Thank you so much,
I had no idea this was already a thing thank you.

You mentioned this working with sdr?
How (or would) this be compatible with use on hacktv's fl2k usb2vga output?
If so,
What would I need to do in short?
Once again, thank you for the info.
Really has been a massive help

**Comment by harrypm** [comment]
@03stevensmi Yeah we have been using a modified FL2K driver [TBC to FL2K](https://github.com/vrunk11/fl2k_2) for Composite/S-Video playback it's iffy on PVMs with some files but if run through modern ICs in TV's it's very stable, this originated with a GNU Radio script.

The commands for that are pretty copy-paste, but the TBC format is not 4fsc sampling exactly the specs are: 

1135x625 For PAL (17727262 Hz) (25i) (560mbps) (4.2GB/min) (252GB/hour)

910x525 For NTSC (14318181 Hz) (29.97i) (453mbps) (3.4GB/min) (204GB/hour)

(Also the FL2K does not output the proper signal voltage its like 0.5~0.7vpp when CVBS is always 1vpp for live signals it really is a cheap way to do it but it's not the most compliant to the standard)
